# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Detent < Formula
  desc "Agent orchestrator for tracker-backed work queues"
  homepage "https://github.com/digitaldrywood/detent"
  version "0.71.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/digitaldrywood/detent/releases/download/v0.71.0/detent_0.71.0_darwin_amd64.tar.gz"
      sha256 "422016fe018970070e7b8bdbcafe66bb097f85c9cc6e70dcda5d3daf249ed96c"

      define_method(:install) do
        bin.install "detent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/digitaldrywood/detent/releases/download/v0.71.0/detent_0.71.0_darwin_arm64.tar.gz"
      sha256 "d7ce233739a2173d6017b0e3215888532e45cf92fed5c6b454e0b7d1e11ba490"

      define_method(:install) do
        bin.install "detent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/digitaldrywood/detent/releases/download/v0.71.0/detent_0.71.0_linux_amd64.tar.gz"
      sha256 "7cf31243417ceff79455de04a37dfbeaf10f431e3520c0fbd8689e1064b09e2c"
      define_method(:install) do
        bin.install "detent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/digitaldrywood/detent/releases/download/v0.71.0/detent_0.71.0_linux_arm64.tar.gz"
      sha256 "09176dcba7e69ce54120f4447519ef13c955e6c4b21cfb699ef6ff36a8b81a89"
      define_method(:install) do
        bin.install "detent"
      end
    end
  end

  test do
    system "#{bin}/detent", "--version"
  end
end
